%%{init: {'theme':'dark'}}%%

sequenceDiagram

    actor user
    participant browser
    participant server

    activate user
    user->>browser: Write "Hello world!" in the input
    user->>browser: Press the Save button
    deactivate user


    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    Note right of browser: content: "Hello world!"<br/>date: new Date()
    activate server
    server-->>browser: 302 Found (triggers a page reload)
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: 200 OK (HTML document)
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: 200 OK (CSS stylesheet)
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: 200 OK (JS script)
    deactivate server

    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: 200 OK [{ ..., "content": "Hello world!", "date": "2025-05-21" }, ... ]
    deactivate server

    Note right of browser: The browser executes the callback function that renders the notes
